### PR TITLE
Compiles with CloudCompare/CloudCompare v2.13.alpha.230227

### PR DESCRIPTION
**Pull request by rjanvier**
Hi @tmontaigu 
I tried to keep things in sync with current 2.13 development branch of CloudCompare.
Maybe I overlooked some modifications but at least it compiles fine with the current master HEAD (CloudCompare/CloudCompare@e76bebd).

### CODE REVIEW

**Comment by tmontaigu** [comment]
Hello, this is cool to fix #13 we may have to modify CloudCompare's.

Could  also need change all references to v2.12.4 to the new sha (grep + replace basically) in the repo (I know the github worflow file and docs/building.rst needs to be updated)

Also before merging i'll need to change the license as its currently GPL, and legally speaking its not the correct one for the intended use

**Comment by rjanvier** [comment]
Thanks a lot Thomas for the review. I think I have updated all the refs. 
Nevertheless, it feels a bit clumsy to rely on a "random" commit in master branch. 
So in additions to the other issue you have mentioned, maybe we could also wait for a dedicated v2.13.alpha1 tag.
cc: @dgirardeau

**Comment by dgirardeau** [comment]
I could tag an arbitrary 2.13.alpha version like this, but it's not stable yet 😅

**Comment by rjanvier** [comment]
Attempt to migrate to v2.13.alpha.230227

**Comment by tmontaigu** [comment]
The sha in https://github.com/tmontaigu/CloudCompare-PythonPlugin/blob/b6ac00c8cb30ee3771ef90950d6fdf6bf7b375c6/wrapper/cccorelib/CMakeLists.txt#L36 also has to be updated to be the same has the cccorelib submodule that is being used in the  v2.13.alpha.230227

**Pull request merged**
