### PR TITLE
Added a missing argument of convertToCloud

### PR DESCRIPTION
**Pull request by Loris-L**
I added the missing argument present in ccRasterGrid header but not in ccRasterGrid.cpp that cause an error when python plugin is compiled with CloudCompare (see #78).

### CODE REVIEW

**Comment by tmontaigu** [comment]
This is probably due to the fact that you compile against the master branch of CloudComapre while we are pinned to an older commits, so the CI is probably going to fail, and will have to change the commit hash used

**Comment by Loris-L** [comment]
So, will we have to wait that source code is updated to updated CloudCompare master branch?

**Comment by tmontaigu** [comment]
No, its that in the CI of this repo we pin the cloudcompare version used to a specific commit for which we know it works

So when making changes that make the come compile with a newer CC commit, the commit hash used in the repo needs to be updated also

I've done it on your branch

**Comment by Loris-L** [comment]
Ok, now it's clear. Thanks for the explanation

**Pull request merged**
